import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DeFeit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a
            href="https://www.globalgradshow.com/project/defeit/"
            target="_blank"
          >
            DeFeit!
          </a>
        </h1>
        <h3>Manufacturer Login:</h3>
        <ConnectButton />
      </main>
    </div>
  );
}
