import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useWeb3React } from "@web3-react/core";
import { InjectedConnector } from "@web3-react/injected-connector";
import { ethers } from "ethers";
import { abi } from "../../constants/abi";

export default function Home() {
  const injected = new InjectedConnector();
  const { activate, active, library: provider } = useWeb3React();
  async function connect() {
    try {
      await activate(injected);
    } catch (e) {
      console.log(e);
    }
  }

  async function execute() {
    if (active) {
      const signer = provider.getSigner();
      const contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
      const contract = new ethers.Contract(contractAddress, abi, signer);
      try {
        await contract.setDrugDetails(
          "Dolo",
          200,
          "qw12-32",
          12,
          120522,
          120523,
          999,
          "My shop",
          "bla bla bla"
        );
      } catch (error) {
        console.log(error);
      }
    } else {
      console.log("Please install MetaMask");
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>DeFeit</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {active ? (
        <>
          Please enter the drug details
          <br />
          <input
            placeholder="Name:"
            name="drugName"
            type="text"
            handleChange={() => {}}
          />
          <br />
          <input
            placeholder="Net Content:"
            name="netContent"
            type="number"
            handleChange={() => {}}
          />
          <br />
          <input
            placeholder="Manufacturer License No.:"
            name="licenseNo"
            type="text"
            handleChange={() => {}}
          />
          <br />
          <input
            placeholder="Batch No.:"
            name="batchNo"
            type="number"
            handleChange={() => {}}
          />
          <br />
          <input
            placeholder="Mfg. Date:"
            name="mfgDate"
            type="text"
            handleChange={() => {}}
          />
          <br />
          <input
            placeholder="Exp. Date:"
            name="expDate"
            type="number"
            handleChange={() => {}}
          />
          <br />
          <input
            placeholder="Price:"
            name="price"
            type="number"
            handleChange={() => {}}
          />
          <br />
          <input
            placeholder="Mfg. By:"
            name="mfgBy"
            type="text"
            handleChange={() => {}}
          />
          <br />
          <input
            placeholder="Ingredients:"
            name="ingredients"
            type="text"
            handleChange={() => {}}
          />
          <br />
          <button onClick={() => execute()}>Save</button>
        </>
      ) : (
        <button onClick={() => connect()}>Connect</button>
      )}
    </div>
  );
}
